name: scout-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pytorch
  - torchvision
  - torchaudio
  - opencv
  - matplotlib
  - plotly
  - trimesh
  - notebook
  - pip
  - pip:
      - opencv-python